### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by zero77** [cschanaj/https-everywhere-issues#1]
Have you thought about creating rulesets as well.
For example, you could scan domains and check if they have a ruleset already and if they support https.
Also, have you run this script against all of the https everywhere rulesets.

**Comment by cschanaj** [comment]
> Have you thought about creating rulesets as well.

No. This repo is only meant to track the progress of some issues I have opened, like https://github.com/EFForg/https-everywhere/issues/9906, https://github.com/EFForg/https-everywhere/issues/9842 and https://github.com/EFForg/https-everywhere/issues/10595, this is NOT an official project or by any means affiliated to EFF. For any generic suggestion, you might want to submit a issue at [`EFForg/https-everywhere/Issues`](https://github.com/EFForg/https-everywhere/issues), or join the discussion in the aforementioned issues. 

> Also, have you run this script against all of the https everywhere rulesets.

Yes, if you are referring to the scripts used to generate the lists in this repo, but I am pretty sure that there are some false results.
